name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: upload
      uses:  actions/upload-artifact@v4.2.0
      with:
        name: build
        path: .
